server:
  port: 8080
  logging:
    level: debug
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: enmotech
    driver-class-name: org.postgresql.Driver
    schema: api
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect